// <auto-generated />
using AltenarAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AltenarAPI.Db.Migrations
{
    [DbContext(typeof(AltenarAPIContext))]
    partial class AltenarAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AltenarAPI.Models.IncomingMessage", b =>
                {
                    b.Property<int>("IncomingMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmptyField")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Session")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VersionBrowser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VersionSystem")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IncomingMessageId");

                    b.ToTable("IncomingMessages");
                });

            modelBuilder.Entity("AltenarAPI.Models.Parameter", b =>
                {
                    b.Property<int>("ParameterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IncomingMessageId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ParameterId");

                    b.HasIndex("IncomingMessageId");

                    b.ToTable("Parameters");
                });

            modelBuilder.Entity("AltenarAPI.Models.Parameter", b =>
                {
                    b.HasOne("AltenarAPI.Models.IncomingMessage", null)
                        .WithMany("Parameters")
                        .HasForeignKey("IncomingMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AltenarAPI.Models.IncomingMessage", b =>
                {
                    b.Navigation("Parameters");
                });
#pragma warning restore 612, 618
        }
    }
}
